feat: implement bottom sheet component (#19)
* feat: implement bottom sheet component

- implement bottom sheet component using framer-motion
- implement useMeasure hook
- implement useWindowSize hook

* test: add bottom sheet to client component

* refactor: implement useMount hook

* refactor: remove unnecessary useMemo and '?.'

* refactor: improve code readability

* refactor: implement useEventListener hook

* refactor: remove unnecessary useEffect deps

* Feat: set kakao map SDK (#18)

* chore(layout): set kakao type

* chore(page): add kakaoMap component for test

* feat(KakaoMap): set test component with marker

* eslint: fix lint error

* fix: set kakao dts and set script self closing

* chore: set typeRoots for dts

* chore: change to kebab case

* refactor: remove annotation and change useEffect import

* refactor: remove annotation

* refactor: use Script and set stratege

* feat: set initialLevel prop

* chore: set self closing

* feat: change var to const and use useRef

* chore: remove unuseful annotation

* feat: set kakao map type"

* eslint: set lint disable for do it only on Mount

* feat: set useMap hook

* feat: set addMarker and changeLocation

* chore: change constans name

* chore: change variable name

* chore: set early return

* chore: set useCallback

* feat: set map component

* feat: set map component

* chore: set ealry return

* chore: change import

* refactor: set correct type to eventType

* feat: set delete and reset marker logic

* fix: fix lint error

* fix: fix build error

* chore: remove annotation and rename markerId

* refactor: use Object.values

* refactor: change type

* fix: fix delete Object

* refactor: update useEventListener hook

* feat: set higher z-index to bottom sheet

* feat: make bottom sheet have three state

- default
- expanded
- collapsed

* feat: make bottom sheet body scrollable

- prevent background from scroll
- add no-scrollbar tailwind utilities

* fix: fix body height calculation

* feat: add ARIA attributes for accessibility

- aria-expanded
- aria-hidden

* fix: move bottom-sheet types to models/interface

to fix Type error: Cannot find type definition file for 'bottom-sheet'. The file is in the program because: Entry point for implicit type library 'bottom-sheet'

* refactor: update variable names

---------

Co-authored-by: Jaeseok <72875894+Pridesd@users.noreply.github.com>